name: tacos
channels:
  - gurobi
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - contourpy=1.2.0
  - cycler=0.12.1
  - fonttools=4.55.0
  - freetype=2.12.1
  - gurobi=12.0.0
  - importlib-resources=6.4.5
  - importlib_resources=6.4.5
  - kiwisolver=1.4.7
  - lcms2=2.16
  - lerc=4.0.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcxx=19.1.4
  - libdeflate=1.22
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libjpeg-turbo=3.0.0
  - libopenblas=0.3.21
  - libpng=1.6.44
  - libsqlite=3.47.0
  - libtiff=4.7.0
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - munkres=1.1.4
  - ncurses=6.5
  - networkx=2.8.8
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.4.0
  - packaging=24.2
  - pandas=2.2.3
  - pillow=11.0.0
  - pip=24.3.1
  - pthread-stubs=0.4
  - pyparsing=3.2.0
  - python=3.9.9
  - python-dateutil=2.9.0.post0
  - python-tzdata=2024.2
  - python_abi=3.9
  - pytz=2024.1
  - qhull=2020.2
  - readline=8.2
  - setuptools=75.6.0
  - six=1.16.0
  - sqlite=3.47.0
  - tk=8.6.13
  - tornado=6.4.2
  - tqdm=4.66.5
  - tzdata=2024b
  - unicodedata2=15.1.0
  - wheel=0.45.1
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xz=5.2.6
  - zipp=3.21.0
  - zstd=1.5.6
